# Generated by Django 5.2.17 on 2026-09-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_remove_workorderevidence_work_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='warranty_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha finaliza garantía'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='warranty_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha inicia garantía'),
        ),
    ]
