# Generated by Django 5.2.17 on 2026-09-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_alter_equipment_warranty_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='supplier_acquisition',
            field=models.CharField(blank=True, choices=[('IMPORMESAN', 'Impormesan'), ('INVERMEDICA', 'Invermedica'), ('SIEMENS', 'SIEMENS'), ('GENERAL_ELECTRIC_HEALTHRARE', 'General electric healthare'), ('TOP_MEDICAL_SYSTEMS', 'Top Medical Systems'), ('STRYKER', 'Stryker'), ('BIOTRONITECH', 'Biotronitech'), ('C_MEDICAL', 'C Medical'), ('MEDICAH', 'Medicah'), ('RX_SAS', 'Rx S.A.S'), ('DRAGER_COLOMBIA', 'Drager Colombia')], max_length=150, verbose_name='Proveedor de acquisión'),
        ),
    ]
