# Generated by Django 5.2.17 on 2026-09-03 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_workordermeasurement_work_order'),
        ('scheduling', '0003_alter_maintenanceschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentworkorder',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order', to='scheduling.maintenanceschedule', verbose_name='Solicitud de origen'),
        ),
    ]
