# Generated by Django 5.2.17 on 2026-09-03 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipmentworkorder_schedule'),
        ('maintenance', '0004_alter_maintenancerecord_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentworkorder',
            name='maintenance_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order', to='maintenance.maintenancerecord', verbose_name='Mantenimiento de origen'),
        ),
    ]
