# Generated by Django 5.2.17 on 2026-09-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_equipmentworkorder_cancel_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorderevidence',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='workordermeasurement',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='workordersignature',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='workordersparepart',
            name='work_order',
        ),
        migrations.DeleteModel(
            name='WorkOrderCost',
        ),
        migrations.DeleteModel(
            name='WorkOrderEvidence',
        ),
        migrations.DeleteModel(
            name='WorkOrderMeasurement',
        ),
        migrations.DeleteModel(
            name='WorkOrderSignature',
        ),
        migrations.DeleteModel(
            name='WorkOrderSparePart',
        ),
    ]
