# Generated by Django 5.2.17 on 2026-09-19 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_alter_workordercost_work_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workordersparepart',
            old_name='unit',
            new_name='unit_cost',
        ),
    ]
