# Generated by Django 5.2.17 on 2026-08-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_initial'),
        ('failures', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='failurerecord',
            constraint=models.CheckConstraint(condition=models.Q(('resolved_at__isnull', True), ('resolved_at__gte', models.F('reported_at')), _connector='OR'), name='failure_resolved_at_after_reported_at'),
        ),
    ]
