# Generated by Django 5.2.17 on 2026-09-18 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0007_remove_workorderevidence_work_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('spare_parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transport_cost', models.DecimalField(decimal_places=12, default=0, max_digits=12)),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='equipment.equipmentworkorder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('PHOTO', 'Fotografía'), ('VIDEO', 'Video'), ('DOCUMENT', 'Documento')], max_length=20)),
                ('description', models.CharField(max_length=250)),
                ('file', models.FileField(blank=True, upload_to='equipment/evidence/')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='equipment.equipmentworkorder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=120)),
                ('expected_value', models.CharField(max_length=100)),
                ('measured_value', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('passed', models.BooleanField(default=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='equipment.equipmentworkorder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TECHNICIAN', 'Technician'), ('ENGINEER', 'Engineer'), ('CLIENT', 'Client'), ('SUPERVISOR', 'Supervisor')], max_length=20)),
                ('signed_by', models.CharField(max_length=150)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='equipment.equipmentworkorder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('reference', models.CharField(max_length=80)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='equipment.equipmentworkorder')),
            ],
        ),
    ]
