# Generated by Django 5.2.17 on 2026-09-19 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_remove_workorderevidence_work_order_and_more'),
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordercost',
            name='work_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='equipment.equipmentworkorder'),
        ),
        # En bases creadas con una version anterior de 0001 este indice ya
        # existe; AlterField lo vuelve a crear identico justo despues.
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS "workorders_workordersparepart_work_order_id_49ca5529";',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='workordersparepart',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='equipment.equipmentworkorder'),
        ),
    ]
