# Generated by Django 5.2.17 on 2026-09-09 13:23
# Archivo reconstruido: quedó aplicada en la BD (email unique) pero no en el repo.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Dirección"),
        ),
        migrations.AlterField(
            model_name="branch",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                unique=True,
                verbose_name="Correo electrónico",
            ),
        ),
    ]
