# Generated by Django 5.2.17 on 2026-09-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observaciones del técnico'),
        ),
    ]
