# Generated by Django 5.2.17 on 2026-09-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancerecord_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='kind',
            field=models.CharField(choices=[('PREVENTIVE', 'Mantenimiento preventivo'), ('CORRECTIVE', 'Mantenimiento correctivo'), ('REPAIR', 'Reparación mayor'), ('CALIBRATION', 'Calibración'), ('INSPECTION', 'Inspección')], db_index=True, max_length=20, verbose_name='Tipo'),
        ),
        migrations.DeleteModel(
            name='EquipmentMaintenanceSchedule',
        ),
    ]
