# Generated by Django 5.2.17 on 2026-09-03 13:14

from django.db import migrations, models


def recreate_schedule_table(apps, schema_editor):
    # Al retroceder, devuelve la tabla que esta migracion elimino para que
    # maintenance.0002 y maintenance.0001 puedan deshacerse sin error.
    model = apps.get_model("maintenance", "EquipmentMaintenanceSchedule")
    if model._meta.db_table not in schema_editor.connection.introspection.table_names():
        schema_editor.create_model(model)


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancerecord_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='kind',
            field=models.CharField(choices=[('PREVENTIVE', 'Mantenimiento preventivo'), ('CORRECTIVE', 'Mantenimiento correctivo'), ('REPAIR', 'Reparación mayor'), ('CALIBRATION', 'Calibración'), ('INSPECTION', 'Inspección')], db_index=True, max_length=20, verbose_name='Tipo'),
        ),
        # La tabla pudo haberse eliminado ya con un nombre de migración viejo
        # (p. ej. maintenance.0003_alter_maintenancerecord_kind_and_more).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name="EquipmentMaintenanceSchedule"),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP TABLE IF EXISTS "maintenance_equipmentmaintenanceschedule" CASCADE;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunPython(
                    migrations.RunPython.noop,
                    reverse_code=recreate_schedule_table,
                ),
            ],
        ),
    ]
