# Generated by Django 5.2.17 on 2026-09-02 18:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceschedule',
            options={'ordering': ['scheduled_date'], 'verbose_name': 'Solicitud de mantenimiento', 'verbose_name_plural': 'Solicitudes de mantenimiento'},
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='requested_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='scheduled_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha programada'),
        ),
    ]
