# Generated by Django 5.2.17 on 2026-09-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_schedule_auto_generated_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='kind',
            field=models.CharField(choices=[('PREVENTIVE', 'Mantenimiento preventivo'), ('REPAIR', 'Reparación')], db_index=True, max_length=20, verbose_name='Tipo'),
        ),
    ]
